<?php
/** @var $block \Catgento\BackToTopNavigation\Block\BackToTopNavigation */
/** @var $escaper \Magento\Framework\Escaper */
?>
<?php
$displayOffsetDesktop = $block->getConfigValue('design/back_to_top_navigation/display_offset_desktop');
$displayOffsetMobile = $block->getConfigValue('design/back_to_top_navigation/display_offset_mobile');
$visibility = $block->getConfigValue('design/back_to_top_navigation/visibility');
$breakpoint = $block->getConfigValue('design/back_to_top_navigation/breakpoint');
?>
<?= $block->getStyle() ?>

<div class="back-top">
    <?= $escaper->escapeHtml($block->getButtonText()); ?>
</div>

<script>
    require([
        'jquery',
        'matchMedia'
    ], function ($) {
        mediaCheck({
            media: '(min-width: <?= $escaper->escapeHtml($breakpoint) ?>px)',

            /**
             * Switch to Desktop Version.
             */
            entry: function () {
                var btn = $('.back-top');

                $(window).scroll(function() {
                    if ($(window).scrollTop() > <?= $escaper->escapeHtml($displayOffsetDesktop) ?>) {
                        btn.fadeIn();
                    } else {
                        btn.fadeOut();
                    }
                });

                btn.on('click', function(e) {
                    e.preventDefault();
                    $('html, body').animate({scrollTop:0}, '300');
                });
            },

            /**
             * Switch to Mobile Version.
             */
            exit: function () {
                var btn = $('.back-top');

                $(window).scroll(function() {
                    if ($(window).scrollTop() > <?= $escaper->escapeHtml($displayOffsetDesktop) ?>) {
                        btn.fadeIn();
                    } else {
                        btn.fadeOut();
                    }
                });

                btn.on('click', function(e) {
                    e.preventDefault();
                    $('html, body').animate({scrollTop:0}, '300');
                });
            }
        });
    });
</script>
