<?php /* @var $block \Catgento\BackToTopNavigation\Block\BackToTopNavigation */ ?>
<?php
$displayOffset = $block->getConfigValue('design/back_to_top_navigation/display_offset');
$visibility = $block->getConfigValue('design/back_to_top_navigation/visibility');
$breakpoint = $block->getConfigValue('design/back_to_top_navigation/breakpoint');
?>
<div style="<?= $block->getStyle() ?>" class="back-top"><?= __('Back to top'); ?></div>

<script>
    require([
        'jquery',
        'matchMedia'
    ], function ($) {
        // Back to top

        <?php if ($visibility != 'both'): ?>
        mediaCheck({
            media: '(min-width: <?= $breakpoint ?>px)',

            <?php if ($visibility == 'desktop'): ?>
            /**
             * Switch to Desktop Version.
             */
            entry: function () {
                initBackToTopNavigation();
            },
            <?php endif; ?>

            <?php if ($visibility == 'mobile'): ?>
            /**
             * Switch to Mobile Version.
             */
            exit: function () {
                initBackToTopNavigation();
            }
            <?php endif; ?>
        });
        <?php else: ?>
        initBackToTopNavigation();
        <?php endif; ?>

        function initBackToTopNavigation() {
            var btn = $('.back-top');

            $(window).scroll(function() {
                if ($(window).scrollTop() > <?= $displayOffset ?>) {
                    btn.fadeIn();
                } else {
                    btn.fadeOut();
                }
            });

            btn.on('click', function(e) {
                e.preventDefault();
                $('html, body').animate({scrollTop:0}, '300');
            });
        }
    });
</script>
